"""esquema inicial

Revision ID: 00d023a7418a
Revises: 
Create Date: 2026-08-08 20:01:48.301894

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '00d023a7418a'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sensor_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sensor_type', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensors_sensor_id'), 'sensors', ['sensor_id'], unique=True)
    op.create_table('readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sensor_id', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.sensor_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_readings_sensor_id'), 'readings', ['sensor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_readings_sensor_id'), table_name='readings')
    op.drop_table('readings')
    op.drop_index(op.f('ix_sensors_sensor_id'), table_name='sensors')
    op.drop_table('sensors')
    # ### end Alembic commands ###
